version: '3.8'

services:
  backend:
    build:
      context: ./  
    ports:
      - "4444:4444"  
    env_file:
      - .env  
    volumes:
      - .:/app  
    depends_on:
      - postgres  
    command: ["npm", "run", "start"] 

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"  # Порт для PostgreSQL
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data  

volumes:
  postgres-data:
